# Generated by Django 5.1.4 on 2025-01-16 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('redes_sociales', models.TextField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('entidad', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], default='activo', max_length=50)),
                ('ARTISTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arte.artista')),
                ('ORGANIZADOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arte.organizador')),
                ('UBICACION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arte.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('hora_evento', models.TimeField()),
                ('contenido_publico', models.TextField()),
                ('imagen_evento', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('estado_publicacion', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=50)),
                ('artistas_presentados', models.ManyToManyField(to='Arte.artista')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publicacion', to='Arte.evento')),
                ('ubicacion_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arte.ubicacion')),
            ],
        ),
    ]
